export const material = [
	{
		id: "1",
		name: "Acetaldehyde",
		MF: 24,
	},
	{
		id: "2",
		name: "Acetic Acid",
		MF: 14,
	},
	{
		id: "3",
		name: "Acetic Anhydride",
		MF: 14,
	},
	{
		id: "4",
		name: "Acetone",
		MF: 16,
	},
	{
		id: "5",
		name: "Acetone Cyanohydrin",
		MF: 24,
	},
	{
		id: "6",
		name: "Acetonitrile",
		MF: 16,
	},
	{
		id: "7",
		name: "Acetyl Chloride",
		MF: 24,
	},
	{
		id: "8",
		name: "Acetylene",
		MF: 29,
	},
	{
		id: "9",
		name: "Acetyl Ethanolamine",
		MF: 14,
	},
	{
		id: "10",
		name: "Acetyl Peroxide",
		MF: 40,
	},
	{
		id: "11",
		name: "Acetyl Salicylic Acid",
		MF: 16,
	},
	{
		id: "12",
		name: "Acetyl Tributyl Citrate",
		MF: 4,
	},
	{
		id: "13",
		name: "Acrolein",
		MF: 29,
	},
	{
		id: "14",
		name: "Acrylamide",
		MF: 24,
	},
	{
		id: "15",
		name: "Acrylic Acid",
		MF: 24,
	},
	{
		id: "16",
		name: "Acrylonitrile",
		MF: 24,
	},
	{
		id: "17",
		name: "Allyl Alcohol",
		MF: 16,
	},
	{
		id: "18",
		name: "Allylamine",
		MF: 16,
	},
	{
		id: "19",
		name: "Allyl Bromide",
		MF: 16,
	},
	{
		id: "20",
		name: "Allyl Chloride",
		MF: 16,
	},
	{
		id: "21",
		name: "Allyl Ether",
		MF: 24,
	},
	{
		id: "22",
		name: "Aluminum Chloride",
		MF: 24,
	},
	{
		id: "23",
		name: "Ammonia",
		MF: 4,
	},
	{
		id: "24",
		name: "Ammonium Nitrate",
		MF: 29,
	},
	{
		id: "25",
		name: "Amyl Acetate",
		MF: 16,
	},
	{
		id: "26",
		name: "Amyl Nitrate",
		MF: 10,
	},
	{
		id: "27",
		name: "Aniline",
		MF: 10,
	},
	{
		id: "28",
		name: "Barium Chlorate",
		MF: 14,
	},
	{
		id: "29",
		name: "Barium Stearate",
		MF: 4,
	},
	{
		id: "30",
		name: "Benzaldehyde",
		MF: 10,
	},
	{
		id: "31",
		name: "Benzene",
		MF: 16,
	},
	{
		id: "32",
		name: "Benzoic Acid",
		MF: 14,
	},
	{
		id: "33",
		name: "Benzyl Acetate",
		MF: 4,
	},
	{
		id: "34",
		name: "Benzyl Alcohol",
		MF: 4,
	},
	{
		id: "35",
		name: "Benzyl Chloride",
		MF: 14,
	},
	{
		id: "36",
		name: "Benzyl Peroxide",
		MF: 40,
	},
	{
		id: "37",
		name: "Bisphenol A",
		MF: 14,
	},
	{
		id: "38",
		name: "Bromine",
		MF: 1,
	},
	{
		id: "39",
		name: "Bromobenzene",
		MF: 10,
	},
	{
		id: "40",
		name: "o-Bromotoluene",
		MF: 10,
	},
	{
		id: "41",
		name: "1,3-Butadiene",
		MF: 24,
	},
	{
		id: "42",
		name: "Butane",
		MF: 21,
	},
	{
		id: "43",
		name: "1-Butene",
		MF: 21,
	},
	{
		id: "44",
		name: "Butyl Acetate",
		MF: 16,
	},
	{
		id: "45",
		name: "Butyl Acrylate",
		MF: 24,
	},
	{
		id: "46",
		name: "n-Butylamine",
		MF: 16,
	},
	{
		id: "47",
		name: "Butyl Chloride",
		MF: 16,
	},
	{
		id: "48",
		name: "2,3-Butylene Oxide",
		MF: 24,
	},
	{
		id: "47",
		name: "Butyl Ether",
		MF: 16,
	},
	{
		id: "49",
		name: "t-Butyl Hydroperoxide",
		MF: 40,
	},
	{
		id: "50",
		name: "t-Butyl Peracetate",
		MF: 40,
	},
];

export const GeneralProcessHazard = [
	{
		id: 1,
		checked: false,
		text: "Exothermic Chemical Reactions",
		userInput: "",
		low: 0.3,
		high: 1.25,
		range: "Enter value between 0.30 to 1.25",
	},
	{
		id: 2,
		checked: false,
		text: "Endothermic Processes",
		userInput: "",
		low: 0.2,
		high: 0.4,
		range: "Enter value between 0.20 to 0.40",
	},
	{
		id: 3,
		checked: false,
		text: "Material Handling and Transfer",
		userInput: "",
		low: 0.25,
		high: 1.05,
		range: "Enter value between 0.25 to 1.05",
	},
	{
		id: 4,
		checked: false,
		text: "Enclosed or Indoor Process Untts",
		userInput: "",
		low: 0.25,
		high: 0.9,
		range: "Enter value between 0.25 to 0.90",
	},
	{
		id: 5,
		checked: false,
		text: "Access",
		userInput: "",
		low: 0.2,
		high: 0.35,
		range: "Enter value between 0.20 to 0.35",
	},
	{
		id: 6,
		checked: false,
		text: "Drainage and Spill Contro",
		userInput: "",
		low: 0.25,
		high: 0.5,
		range: "Enter value between 0.25 to 0.50",
	},
];

export const SpecialProcessHazard = [
	{
		id: 1,
		checked: false,
		text: "Toxic Material(s)",
		userInput: "",
		low: 0.2,
		high: 0.8,
		range: "Enter value between 0.20 to 0.80",
	},
	{
		id: 2,
		checked: false,
		text: "Sub-Atmospheric Pressure « 500 mm Hg)",
		userInput: "",
		low: 0.5,
		high: 0.5,
		range: "Enter value 0.50",
	},
	{
		id: 3,
		checked: false,
		text: "Dust Explosion",
		userInput: "",
		low: 0.25,
		high: 2.0,
		range: "Enter value between 0.25 to 2.00",
	},
	{
		id: 4,
		checked: false,
		text: "Low Temperature",
		userInput: "",
		low: 0.2,
		high: 0.3,
		range: "Enter value between 0.20 to 0.30",
	},
	{
		id: 5,
		checked: false,
		text: "Corrosion and Erosion",
		userInput: "",
		low: 0.1,
		high: 0.75,
		range: "Enter value between 0.10 to 0.75",
	},
	{
		id: 6,
		checked: false,
		text: "Leakage - Joints and Packing",
		userInput: "",
		low: 0.1,
		high: 1.5,
		range: "Enter value between 0.10 to 1.50",
	},
	{
		id: 7,
		checked: false,
		text: "Hot Oil Heat Exchange System",
		userInput: "",
		low: 0.15,
		high: 1.15,
		range: "Enter value between 0.15 to 1.15",
	},
	{
		id: 8,
		checked: false,
		text: "Hot Oil Heat Exchange System",
		userInput: "",
		low: 0.5,
		high: 0.5,
		range: "Enter value 0.50",
	},
];

export const Process_Control_Credit_Factor = [
	{
		id: 1,
		checked: false,
		text: "Emergency Power",
		userInput: "",
		low: 0.98,
		high: 0.98,
		range: "Enter value 0.98",
	},
	{
		id: 2,
		checked: false,
		text: "Cooling",
		userInput: "",
		low: 0.97,
		high: 0.99,
		range: "Enter value between 0.97 to 0.98",
	},
	{
		id: 3,
		checked: false,
		text: "Explosion Control",
		userInput: "",
		low: 0.84,
		high: 0.98,
		range: "Enter value between 0.84 to 0.98",
	},
	{
		id: 4,
		checked: false,
		text: "Emergency Shutdown",
		userInput: "",
		low: 0.96,
		high: 0.99,
		range: "Enter value between 0.96 to 0.99",
	},
	{
		id: 5,
		checked: false,
		text: "Computer Control",
		userInput: "",
		low: 0.93,
		high: 0.99,
		range: "Enter value between 0.93 to 0.99",
	},
	{
		id: 6,
		checked: false,
		text: "Inert Gas",
		userInput: "",
		low: 0.94,
		high: 0.96,
		range: "Enter value between 0.94 to 0.96",
	},
	{
		id: 7,
		checked: false,
		text: "Operaling InstructionslProcedures",
		userInput: "",
		low: 0.15,
		high: 1.15,
		range: "Enter value between 0.91 to 0.99",
	},
	{
		id: 8,
		checked: false,
		text: "Reactive Chemical Review",
		userInput: "",
		low: 0.91,
		high: 0.98,
		range: "Enter value between 0.91 to 0.98",
	},
	{
		id: 9,
		checked: false,
		text: "Other Process Hazard Analysis",
		userInput: "",
		low: 0.91,
		high: 0.98,
		range: "Enter value between 0.91 to 0.98",
	},
];

export const Material_Isolation_Credit_Factor = [
	{
		id: 1,
		checked: false,
		text: "Remote Control Valves",
		userInput: "",
		low: 0.96,
		high: 0.98,
		range: "Enter value between 0.96 to 0.98",
	},
	{
		id: 2,
		checked: false,
		text: "Dump/Blowdown",
		userInput: "",
		low: 0.96,
		high: 0.98,
		range: "Enter value between 0.96 to 0.98",
	},
	{
		id: 3,
		checked: false,
		text: "Drainage",
		userInput: "",
		low: 0.91,
		high: 0.97,
		range: "Enter value between 0.91 to 0.97",
	},
	{
		id: 4,
		checked: false,
		text: "Inlerlock",
		userInput: "",
		low: 0.98,
		high: 0.98,
		range: "Enter value 0.98",
	},
];

export const Fire_Protection_Credit_Factor = [
	{
		id: 1,
		checked: false,
		text: "Leak Detection",
		userInput: "",
		low: 0.94,
		high: 0.98,
		range: "Enter value between 0.94 to 0.98",
	},
	{
		id: 2,
		checked: false,
		text: "Structural Steel",
		userInput: "",
		low: 0.95,
		high: 0.98,
		range: "Enter value between 0.95 to 0.98",
	},
	{
		id: 3,
		checked: false,
		text: "Fire Waler Supply",
		userInput: "",
		low: 0.94,
		high: 0.97,
		range: "Enter value between 0.94 to 0.97",
	},
	{
		id: 4,
		checked: false,
		text: "Special Syslems",
		userInput: "",
		low: 0.91,
		high: 0.91,
		range: "Enter value 0.91",
	},
	{
		id: 5,
		checked: false,
		text: "Sprinkler Systems",
		userInput: "",
		low: 0.74,
		high: 0.97,
		range: "Enter value between 0.74 to 0.97",
	},
	{
		id: 6,
		checked: false,
		text: "Water Curtains",
		userInput: "",
		low: 0.97,
		high: 0.98,
		range: "Enter value between 0.97 to 0.98",
	},
	{
		id: 7,
		checked: false,
		text: "Foam",
		userInput: "",
		low: 0.92,
		high: 0.97,
		range: "Enter value between 0.92 to 0.97",
	},
	{
		id: 8,
		checked: false,
		text: "Hand Extinguishers/Monilors",
		userInput: "",
		low: 0.93,
		high: 0.98,
		range: "Enter value between 0.93 to 0.98",
	},
	{
		id: 9,
		checked: false,
		text: "Cable Prolection",
		userInput: "",
		low: 0.94,
		high: 0.98,
		range: "Enter value between 0.94 to 0.98",
	},
];

export const Additional_Information = [
	{
		id: 1,
		checked: false,
		text: "Radius of Exposure",
		userInput: "",
		low: 0.96,
		high: 0.98,
		range: "Enter value between 0.96 to 0.98",
	},
	{
		id: 2,
		checked: false,
		text: "Dump/Blowdown",
		userInput: "",
		low: 0.96,
		high: 0.98,
		range: "Enter value between 0.96 to 0.98",
	},
	{
		id: 3,
		checked: false,
		text: "Drainage",
		userInput: "",
		low: 0.91,
		high: 0.97,
		range: "Enter value between 0.91 to 0.97",
	},
	{
		id: 4,
		checked: false,
		text: "Inlerlock",
		userInput: "",
		low: 0.98,
		high: 0.98,
		range: "Enter value 0.98",
	},
];
